### ISSUE TITLE
[bug] NextJS Hydration error causes web3modal to no longer open

### ISSUE THREAD

**Issue by mlenser** [WalletConnect/web3modal#1386] opened 2023-10-10 14:25 UTC
### Link to minimal reproducible example

https://github.com/mlenser/web3modal-w3m-account-button-already-used/tree/only-app-router-oct-10-2023

**Steps to reproduce:**

- Go to https://web3modal-w3m-account-button-already-used-moaribp1i-astaria-xyz.vercel.app
- Connect a wallet
- Click the "Other" link at the top to go to https://web3modal-w3m-account-button-already-used-moaribp1i-astaria-xyz.vercel.app/other
- Refresh the page
- Try clicking "Open Connect Modal" button again. Nothing happens.

### Summary

Thanks again for releasing `3.1.0`. Our core issue is more clear now. It seems the web3modal stops working if there is a hydration error.

You can see the hydration error if you run the app locally. https://legacy.reactjs.org/docs/error-decoder.html/?invariant=418 and https://legacy.reactjs.org/docs/error-decoder.html/?invariant=423 will be shown in the console on the preview.

Every other part of our still works so this seems unique to web3modal. Though perhaps other apps are failing more gracefully? Not sure.

### List of related npm package versions

Latest versions:
```
    "@web3modal/wagmi": "^3.1.0",
    "next": "13.5.4",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^1.15.1",
    "wagmi": "^1.4.3"
```

**Comment by mlenser** [comment] 2023-10-10 14:45
`web3modal`, `WagmiConfig`, and `HydrationError` are rendered on the client. `HydrationError` is causing the hydration error due to `wagmi`'s `useAccount`, but the hydration error shouldn't cause `web3modal` to stop working, should it?

Every other part of our still works so this seems unique to web3modal. Though perhaps other apps are failing more gracefully?

**Comment by 0xAsimetriq** [comment] 2023-10-10 14:55
Will need to dive deeper tomorrow, but when `Other` page is loaded up as first one web3modal is not even created, so that hydration error is thrown beforehand, and the fact that it is means that wagmi's hook is still being rendered on the server. Shot in the dark, but does moving components folder inside `app` one solve the trick? Every bit of nexts documentation uses this directive from within app folder.

<img width="459" alt="Screenshot 2023-10-10 at 17 53 44" src="https://github.com/WalletConnect/web3modal/assets/3154053/4a87babf-e99b-4d2a-9b92-b615a47f9b14">

**Comment by glitch-txs** [comment] 2023-10-10 15:20
RSC and SSR are different things, using CSC you will still get the SSR functionality the same way as in the pages directory config.

To give a little bit more context:
Wagmi uses localStorage to store session data (address, chains, etc). During SSR you will get your components rendered on the server first and then on the client, if what's displayed on the DOM doesn't not match with what was rendered on the server Next will throw this error. This happens because in the server the user wasn't connected since there's no localStorage there.

**Comment by glitch-txs** [comment] 2023-10-10 15:41
I personally like to use this component, then I wrap some Wagmi outputs with it
https://github.com/glitch-txs/simple-web3-app/blob/main/src/components/utils/Hydrate.tsx

**Comment by glitch-txs** [comment] 2023-10-10 16:38
This needs to be fixed by Wagmi internally, @web3modal/wagmi is bind to Wagmi

**Comment by mlenser** [comment] 2023-10-10 18:48
A Radix dialog still opens when there is a hydration error. `web3modal` does not.
The hydration error is caused by a server mismatch which in this case is caused by `wagmi`, though I'd be surprised if the modal opened with a hydration error not caused by `wagmi`.
I can put together a reproduction of that case to see what happens.
If `web3modal` isn't interactable with a generic hydration error, then would it be valid for `web3modal` to fix?

**Comment by mlenser** [comment] 2023-10-10 19:19
**Reproduction for that case:**

https://github.com/mlenser/web3modal-w3m-account-button-already-used/tree/only-app-router-oct-10-2023-hydration-without-wagmi

- Go to https://web3modal-w3m-account-button-already-use-git-562341-astaria-xyz.vercel.app/other
- Click the "Open Connect Modal". Nothing happens. No console errors or anything.
- Click the "Open Radix dialog". The Radix dialog opens.

**Comment by 0xAsimetriq** [comment] 2023-10-11 06:29
Web3Modal relies on sucessful init of wagmiConfig (that is then passed to it during `createWeb3Modal`), somewhere down the line this fails, hence modal is not created. it doesn't open on the page, because it doesn't exist on it. Now the issue is figuring out why hydration error happens in the first place if you have that `use client` directive, wagmi should only be used on client.

Radix is unrelated, it doesn't depend on wagmi.

I'll keep this open for a bit to further investigate, but I believe dynamic imports suggested by glitch / some kind of fix on wagmi's end is ultimately what's needed to get this going.

**Comment by mlenser** [comment] 2023-10-11 08:10
Radix was used as an example of an interactive dialog that works when there is a hydration error.

Wagmi also works when there is a hydration error:

https://github.com/mlenser/web3modal-w3m-account-button-already-used/tree/only-app-router-hydration-with-wagmi

- Go to https://web3modal-w3m-account-button-already-use-git-1cc77d-astaria-xyz.vercel.app
- Click the "Open Connect Modal" and connect a wallet.
- Click "Hydration error with wagmi" which will take you to https://web3modal-w3m-account-button-already-use-git-1cc77d-astaria-xyz.vercel.app/hydration-error-wagmi
- The address of the connected wallet is shown which means that `wagmi` works when there is a hydration error
- `web3modal` does not work when there is a hydration error. It does not open when clicked.

`useAccount` from `wagmi` wouldn't work unless `WagmiConfig` initiated successfully. So it doesn't seem like a `wagmi` issue.

**Comment by glitch-txs** [comment] 2023-10-11 15:28
Hi, as previously stated this is related to Wagmi and not Web3Modal on its own, by catching all possible errors from Wagmi you shouldn't be facing any hydration errors + they are expected to be handled by the dapp.
The address is stored in Wagmi's store (Zustand) and this is a potential trigger of hydration mismatch. (e.g. the address wasn't showing up during the server side render but it doesn't on the client one).

I'll be close this as unplanned for now as the only way to solve this, as far as we know ,is from Wagmi's source code. We also don not expect to handle hydration errors on Web3Modal side as we don't expect this errors to happen at all on an application.

Some more context:

- https://github.com/wagmi-dev/wagmi/issues/542#issuecomment-1144178142
- https://github.com/wagmi-dev/wagmi/issues/28#issuecomment-1005160238
- https://github.com/wagmi-dev/wagmi/discussions/2207#discussioncomment-5681242

For Web3Modal v3 ethers we do expect solving this issue since we're building it from scratch.

Possible solution: Propose to the Wagmi team to handle this on their side.

**Comment by mlenser** [comment] 2023-10-11 15:59
**This issue isn't related to `wagmi`. This issue is that `web3modal` does not responde when there is a runtime error.** That runtime error could be for many reasons:

- Hydration errors unrelated to wagmi. The reproduction above shows `web3modal` failing without `wagmi` causing any hydration issues. The hydration issue is caused by a `<div>` in a `<p>`.
- Hydration errors caused by wagmi - Sure, `wagmi` shouldn't cause hydration errors, but that's not really the core issue
- Other runtime errors

Our app could randomly have runtime errors. Any app could. We're taking extreme measures to avoid those, but they can occur. When they do occur `web3modal` does not work.

> We also do not expect to handle hydration errors on Web3Modal side as we don't expect this errors to happen at all on an application.

I can open a more generic issue with a runtime error if so desired. There is still an issue of `web3modal` not working when there is a runtime error while other libraries continue to work.

**Comment by glitch-txs** [comment] 2023-10-11 16:41
> The hydration issue is caused by a <div> in a <p>.
 
 we'll look into this 👍

**Comment by glitch-txs** [comment] 2023-10-12 02:15
hi @mlenser do you know any other runtime error cases for this issue besides hydration ones?

**Comment by mlenser** [comment] 2023-10-12 13:26
My main concern is that runtime errors are difficult to fully eliminate. We can't use any static tools like typescript, eslint, etc.

With some errors (at least the hydration one) the app fails gracefully and still works (except `web3modal`). Others the whole app fails/falls back to the NextJS error page.

**Some other situations that I've encountered and would be be wary of:**
-  **[Not a runtime error]** When a NextJS page "[deopted into client-side rendering](https://nextjs.org/docs/messages/deopted-into-client-rendering)" the `web3modal` did not open. I solved this on our app by removing the `useSearchParams` from certain pages and then `web3modal` worked on those pages. I tried to create a reproduction of this issue this morning, but was unable to get the pages to deopt into client-side rendering. If that occurs `web3modal` doesn't work. I'm not sure why since client should be ideal. I'll try to create a reproduction of this. 
- **[Runtime error (fails gracefully)]** Hydration issues that we've discussed above. `<div>` in `<p>` cannot be statically checked in all cases so it could slip through, causing `web3modal` to not work unless every page is manually tested. I know hydration issues from `wagmi` aren't your concern and that's fair, but there are other types that could slip through.
- **[Runtime error (?)]** API or blockchain response might return unexpected data. Personally, we're typing it with zod, but there may be cases for a runtime error. I'm not sure if it'd fail gracefully or not.
- **[Runtime error (?)]** Javascript errors such as BigInt/BigNumber. We have occasionally seen overflows/underflows and other cases of converting to/from, especially when we have user input. We've hopefully covered all cases, but I've seen some that fail gracefully in the past. I'm not sure how `web3modal` would handle them.

**Cases that I'm not concerned about:**

- **[Runtime error (hard fail)]** `throw new Error` for example. The whole app seems to break/fallback to an error page so `web3modal` isn't a concern here.

**Comment by glitch-txs** [comment] 2023-10-12 17:34
Thanks for sharing we'll look into this.

So far I found that the hydration error blocks/removes when trying to create and append a child element to the body, this is what Web3Modal does and why it fails (I assume) during this error. We'll investigate it.

Aside from the issue, I'm curious, how do you like the app router so far compared to pages?

**Comment by mlenser** [comment] 2023-10-16 09:32
We're very happy with App router. Our pages are now significantly smaller in size as App router handles the bundle much better and the App router experience is nice.

We can't take advantage of the server on most pages as most of our data comes from the blockchain and wagmi can't handle that currently, but App router is still worth the effort imo.

**Comment by abdullahmehboob20s** [comment] 2023-10-16 15:31
I fixed it by wrapping my connect wallet button in this component 
`<NonSSRWrapper></NonSSRWrapper>`

so my component is looking like this

`"use client";

import { useWeb3Modal } from "@web3modal/wagmi/react";
import { BiLogOut } from "react-icons/bi";
import { useAccount, useConnect } from "wagmi";
import NonSSRWrapper from "./NonSSRWrapper";

function shortenAddress(address) {
  // Check if the address is valid and has at least 8 characters
  if (address && address.length >= 8) {
    const start = address.slice(0, 4);
    const end = address.slice(-4);
    return `${start}....${end}`;
  }
  // Return the original address if it's not valid
  return address;
}

export default function ConnectWalletButton() {
  const { open } = useWeb3Modal();
  const { address, isConnecting } = useAccount();

  return (
    <>
      <NonSSRWrapper>
        <button
          disabled={isConnecting}
          className="py-1 px-[1em] rounded text-xs xl:text-sm border-2 border-purple disabled:opacity-60 disabled:pointer-events-none"
          onClick={() => open({ view: address ? "Account" : "Connect" })}
        >
          {address ? (
            <>
              <BiLogOut className="inline-block text-[1.3em] relative bottom-[.08em] mr-[.1em]" />{" "}
              {shortenAddress(address)}
            </>
          ) : (
            "Connect Wallet"
          )}
        </button>
      </NonSSRWrapper>
    </>
  );
}
`

this is `NonSSRWrapper` component looks like

`import dynamic from "next/dynamic";
import React from "react";

const NonSSRWrapper = (props) => (
  <React.Fragment>{props.children}</React.Fragment>
);
export default dynamic(() => Promise.resolve(NonSSRWrapper), {
  ssr: false,
});
`

**Comment by abdullahmehboob20s** [comment] 2023-10-19 11:16
I was having this warning `Entire page /patent deopted into client-side rendering` while building my Nextjs 13 app, and I was having this warning in my 31 pages, But I was not having this warning of those pages which are outside of [Route Groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups). But I really wanted to use Route Groups.

So I came up with the solution which looks like this.

my whole app is wrapped in a provider, so my `layout.js` is looking like this.
```javascript
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider>
          <Layout>{children}</Layout>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
```

my `Web3ModalProvider` contained a wev3modal implementation which looks like below. I wrapped this whole component in `NonSSRWrapper` which solved this warning `Entire page /patent deopted into client-side rendering` while building my application.
```javascript
"use client";

import { WagmiConfig } from "wagmi";
import { config, projectId, chains } from "utils/wagmiConfig";
import { createWeb3Modal } from "@web3modal/wagmi/react";
import { AppProgressBar } from "next-nprogress-bar";
import NonSSRWrapper from "./NonSSRWrapper";

createWeb3Modal({
  wagmiConfig: config,
  projectId,
  chains,
});

export default function Web3ModalProvider({ children }) {
  return (
    <NonSSRWrapper>
      <WagmiConfig config={config}>
        {children}

        <AppProgressBar
          height="3px"
          color="#7e20fc"
          options={{ showSpinner: false }}
          shallowRouting
        />
      </WagmiConfig>
    </NonSSRWrapper>
  );
}
```

`NonSSRWrapper` component looks like this 
```javascript
import dynamic from "next/dynamic";
import React from "react";

const NonSSRWrapper = (props) => (
  <React.Fragment>{props.children}</React.Fragment>
);
export default dynamic(() => Promise.resolve(NonSSRWrapper), {
  ssr: false,
});
```

**Comment by mlenser** [comment] 2023-10-19 11:22
What you've done is ensure none of your app is SSR.

> It allows you to defer loading of Client Components and imported libraries, and only include them in the client bundle when they're needed.

https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading

It works, but it defeats the point of NextJS.

**Comment by abdullahmehboob20s** [comment] 2023-10-19 13:13
> What you've done is ensure none of your app is SSR.
> 
> > It allows you to defer loading of Client Components and imported libraries, and only include them in the client bundle when they're needed.
> 
> https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading
> 
> It may work, but it defeats the point of NextJS.

I checked it by placing console.log in `./page.js` which is the root page, it was showing on server ( in vscode terminal ). I don't know If there is any other way to validate it.

**Comment by enesozturk** [comment] 2023-12-15 11:20
Hey all, following the conversations, as previously mentioned, if you're using a technology that allows server-side rendering, you need to make sure that the w3m is rendered only on the client side. 

As we updated our [documents for the Next.js](https://docs.walletconnect.com/web3modal/nextjs/about?platform=wagmi#implementation), you can see that we're creating a custom provider component with the `use client;` directive, which will ensure it's only rendered on the client side. Currently, due to the mechanism of `wagmi`, we cannot do server-side rendering right now. So it's expected to see hydration issues if you try to.

⚡️👉 Hopefully, it's in the wagmi team's plan to provide first-class SSR support for the v2.

Currently, closing the issue since it has low activity. Thank you for your support

**Closed** 2024-01-30 14:04 UTC
Labels: bug, needs review

**Comment by glitch-txs** [comment] 2024-01-30 14:23
unable to reproduce in v4

**Comment by mlenser** [comment] 2024-01-30 19:03
Great to hear! I'll investigate once v4 is stable as the upgrade is quite large with viem, wagmi, and web3modal all having breaking changes that are related.

**Comment by chris-covali** [comment] 2024-05-08 11:27
Reproduceable on 4.1.11

**Comment by swastikmishra** [comment] 2024-05-25 14:30
```tsx
{/* @ts-ignore */}
<w3m-modal></w3m-modal>
```
Adding the Web Component directly in the `layout.tsx` does the job.
I figured out, Nextjs virtual DOM and SSR is not able to track Web Components properly during hydration.
