### ISSUE TITLE
React examples do not work

### ISSUE THREAD

**Issue by ngmisl** [WalletConnect/web3modal#848] opened 2023-01-29 12:47 UTC
getting a 

`Unhandled Runtime Error
TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.`

**Comment by 0xAsimetriq** [comment] 2023-01-29 16:48
We'll need more details on this i.e. how did you set up the example, did you change anything etc. Also did you follow https://github.com/WalletConnect/web3modal/blob/V2/.github/docs/development.md

**Comment by 0xAsimetriq** [comment] 2023-01-30 08:15
Just pulled fresh repo for V2 branch and had no issues. Did you run `yarn dev` and `yarn dev:react` in separate terminal tabs?

**Comment by leoanhvig** [comment] 2023-01-30 09:41
I also got the same error. 
<img width="579" alt="Screenshot 2023-01-30 at 16 39 41" src="https://user-images.githubusercontent.com/115066317/215441683-9ef55442-fa3d-4159-9a22-72131560894e.png">

**Comment by leoanhvig** [comment] 2023-01-30 09:41
![Screenshot 2023-01-30 at 16 39 30](https://user-images.githubusercontent.com/115066317/215441945-ff2aca26-c381-42ce-9df0-79d4561c29e6.png)

**Comment by 0xAsimetriq** [comment] 2023-01-30 12:09
@leoanhvig I noticed you are cd'ing into examples folder to execute commands, ensure you do this

1. Pull repo
2. Run `yarn install; yarn build; yarn dev` from the root of the monorepo
3. Run `yarn dev:react` in a separate terminal window from the root of the monorepo

**Comment by oanhlewkm** [comment] 2023-01-31 02:33
i pulled back the repo again, followed the steps you instructed but when i run yarn build it still has the error, run yarn dev:react it keeps giving the css error as above 
![Screenshot 2023-01-31 at 09 28 01](https://user-images.githubusercontent.com/38484322/215647669-bc7207bf-23aa-47bf-b64b-eb42c54ba1b6.png)
![Screenshot 2023-01-31 at 09 31 23](https://user-images.githubusercontent.com/38484322/215647722-75dcdc05-b5d7-49f3-bae2-8bccc090ac0e.png)
![Screenshot 2023-01-31 at 09 31 28](https://user-images.githubusercontent.com/38484322/215647763-cfde7f15-cfb5-4da0-ae62-1cfa968e42d4.png)

**Comment by leoanhvig** [comment] 2023-01-31 02:34
i pulled back the repo again, followed the steps you instructed but when i run yarn build it still has the error, run yarn dev:react it keeps giving the css error as above 
![Screenshot 2023-01-31 at 09 28 01](https://user-images.githubusercontent.com/38484322/215647669-bc7207bf-23aa-47bf-b64b-eb42c54ba1b6.png)
![Screenshot 2023-01-31 at 09 31 23](https://user-images.githubusercontent.com/38484322/215647722-75dcdc05-b5d7-49f3-bae2-8bccc090ac0e.png)
![Screenshot 2023-01-31 at 09 31 28](https://user-images.githubusercontent.com/38484322/215647763-cfde7f15-cfb5-4da0-ae62-1cfa968e42d4.png)

**Comment by 0xAsimetriq** [comment] 2023-01-31 09:43
Really strange, will look into this once we release 2.1, but this same setup is ran by our devs locally and on our CI's. Did you by any chance modify the examples somehow, or all of this is fresh from the github repo?

**Comment by leoanhvig** [comment] 2023-01-31 10:00
I just added the .env.local file like the following and didn't modify any of the repo's files
![Screenshot 2023-01-31 at 16 59 43](https://user-images.githubusercontent.com/115066317/215728816-26a919fe-3975-4072-bac0-1fd83f9605fb.png)

**Comment by flopez7** [comment] 2023-01-31 11:54
I also followed the steps you mentioned without making any changes in the code and I got the same error

**Comment by flopez7** [comment] 2023-01-31 13:50
@0xAsimetriq Standalone worked for me. I'm using node v18.12.1 and yarn 1.22.19. Anyway, I have tried to import it into a project as it comes in the documentation but I also get errors. I am using the following versions @web3modal/ethereum: 2.0.0, @web3modal/react: 2.0.0, Wagmi I have tried from 0.10.11 to 0.11.2 as you mention here #839 but it doesn't work. If I comment out the lines that give typing error as you mention, it lets me compile it but I also get an error with the wagmi client. I have tried to do what it says here #764 but it still doesn't work.

**Comment by shavidzet** [comment] 2023-01-31 13:59
A very related issue here with examples.
I tested `examples/react` and `examples/react-standalone`.

**Steps to reproduce:**
1. Navigate to `examples/react` or `examples/react-standalone`
2. Install npm dependencies by running: `yarn install`
3. Up and running the app by running: `yarn dev`
4. Visiting the app in the browser.
![image](https://user-images.githubusercontent.com/9953430/215780360-11eb8969-95ee-4a1f-a3f2-3c34cc35fd5d.png)

**Specs:**
![image](https://user-images.githubusercontent.com/9953430/215780625-312660fa-7ee4-4833-a7ee-988876bf7c97.png)

**Comment by leoanhvig** [comment] 2023-02-01 01:55
@0xAsimetriq 
![Screenshot 2023-02-01 at 08 54 18](https://user-images.githubusercontent.com/115066317/215925935-9347a37b-5559-4f23-b7b1-d75d61029cb8.png)

**Comment by leoanhvig** [comment] 2023-02-01 02:00
i have just run react-standalone and got the same error 
![Screenshot 2023-02-01 at 08 58 18](https://user-images.githubusercontent.com/115066317/215926448-5a17684e-34a7-4a6f-8396-32f0349920cb.png)
![Screenshot 2023-02-01 at 09 00 25](https://user-images.githubusercontent.com/115066317/215926682-6f7db771-fc90-46dc-b0db-e25c8ca034d0.png)

**Comment by shavidzet** [comment] 2023-02-06 12:19
@0xAsimetriq Yeah, it's supported by all modern browsers: https://caniuse.com/?search=web%20components

This issue is not related to browser compatibility.

**Comment by memochou1993** [comment] 2023-02-07 05:26
I got the same error

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/38420282/217155971-66e44897-d11c-42fb-880f-70d985a7ee20.png">

**Comment by SeongHo-Won** [comment] 2023-02-16 09:50
i have just run react-standalone and got the same error too

**Comment by 0xAsimetriq** [comment] 2023-02-16 09:53
@SeongHo-Won DO you mean [nextjs-standalone](https://github.com/WalletConnect/web3modal/tree/V2/examples/nextjs-standalone)?

Also could you please outline which steps you performed before getting that error (the more details the better 🙏 )

**Comment by Exaustia** [comment] 2023-02-27 15:58
Hello, 
Get the same error to.
My step is: 
Pull the github, navigate in examples/nextJS folder then
- Updated the .env with my project ID 
- yarn innstall
- yarn dev

Then got this error : 
![image](https://user-images.githubusercontent.com/10464243/221614047-04bbf745-3c4c-41ab-8cb8-8514152eefcd.png)

**Comment by liumenghua** [comment] 2023-03-16 08:29
same error

**Comment by 0xAsimetriq** [comment] 2023-03-17 08:10
After several attempts of trying to recreate the issue, we were not able to, so will be closing this.

However, I recorded a video of me getting our lab example going from the scratch, I hope it can help (basically same flow for any other example).

In the video I

1. Clone / Download the project (un-zip it if needed)
2. Install dependencies
3. While dependencies are installing I grab my projectID
4. Once installed, I add `.env.local` file with my project id to example
5. I then build the monorepo
6. I run `yarn dev` in first terminal window to build all packages in watch mode
7. I then run `yarn dev:lab` to run laboratory example in a separate terminal window

Remember, all of these commands are ran from a monorepo root. In your own apps you can just reference the examples, you don't need to compile monorepo since in your case dependencies will be installed from npm not local.

https://user-images.githubusercontent.com/3154053/225848425-8b999662-c169-4e42-8329-8820a7e40d70.mov

**Closed by 0xAsimetriq** 2023-03-17 08:10 UTC
Labels: bug, in review
