### ISSUE TITLE
unable to run "Getting started" code

### ISSUE THREAD

**Issue by fibo** [WalletConnect/web3modal#648] opened 2022-10-23 16:53 UTC
**Describe the bug**
Cannot run React example from docs. If the app is using TypeScript it even crashes.

**SDK Version**
 - Version 2.0.0-alpha.7

**To Reproduce**
Just followed "Getting Started" here:

1. `npm install @web3modal/react @web3modal/ethereum ethers`
2. set this code

```js
import { ConnectButton, Web3Modal } from '@web3modal/react'

const config = {
  projectId: '<YOUR_PROJECT_ID>', // Here I added the projectId I got on cloud.walletconnect.com
  theme: 'dark',
  accentColor: 'default',
  ethereum: {
    appName: 'myApp' // Here added the project name I created on cloud.walletconnect.com
  }
}

export default function App() {
  return (
    <>
      <ConnectButton />
      <Web3Modal config={config} />
    </>
  )
}
```

Question 1: I am running it locally, I could not add "localhost" on my cloud.walletconnect.com project allowed domains. Is it relevant?
Question 2: should the appName in the config match the project name on cloud.walletconnect.com project?
Question 3: Am I missing something?

**Expected behavior**
Simply connect, I expect as a developer that it is easy to connect and the documentation is understandable or that I get some clear error message.

**Screenshots**
Also I got this message from MetaMask: Connection Declined.

<img width="443" alt="Screenshot 2022-10-23 at 18 53 05" src="https://user-images.githubusercontent.com/176730/197404975-7d520f4b-df83-4412-a378-22908ff36f4f.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone13 mini
 - Browser Safari

**Additional context**
On a React app using only JS, I was not able to connect Metamask.
I tried on mobile also with TrustWallet, got no result.
Tried also on React app based on TS.

By the way I am getting also this warning

```
WARNING in ./node_modules/json-rpc-engine/dist/mergeMiddleware.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/io/Code/my-app/node_modules/json-rpc-engine/src/mergeMiddleware.ts' file: Error: ENOENT: no such file or directory, open '/Users/io/Code/my-app/node_modules/json-rpc-engine/src/mergeMiddleware.ts'
```

**Comment by IljaDaderko** [comment] 2022-10-24 07:00
@fibo any chance you could provide link to repo that reproduces this issue? Hard to tell what could be wrong atm just from the info above

**Comment by fibo** [comment] 2022-10-24 09:41
@IljaDaderko repo here: https://github.com/fibo/hello-walletconnect

on https://web3modal.pages.dev/ I can connect using my iPhone

if I start the webapp in the repo linked, I cannot

**Comment by IljaDaderko** [comment] 2022-10-24 09:53
@fibo are you accessing `localhost` on your iPhone? I think there i an issue with that flow that's not related to web3modal. Any chance you can deploy your example to provider like vercel or cloudflare and check if you are able to connect that way?

**Comment by IljaDaderko** [comment] 2022-10-24 09:56
Here is similar issue with localhost testing on the phone https://github.com/WalletConnect/web3modal/issues/633 wonder if you are running into something like this.

**Comment by fibo** [comment] 2022-10-24 09:57
I am using local IP address to access from my phone, e.g. http://192.168.1.51:3000

No, even if me or you try to deploy it online: as a developer I need to use it locally.

@IljaDaderko did you tried to run it?

**Comment by fibo** [comment] 2022-10-24 09:58
> Here is similar issue with localhost testing on the phone #633 wonder if you are running into something like this.

no, the iPhone and Desktop do not connect as reported.

**Comment by IljaDaderko** [comment] 2022-10-24 10:36
@fibo Could you try following and let me know if it resolves the issue please

1. Delete `node_modules`
2. Delete package-lock.json
3. Install alpha.8

I replicated your issue on `alpha.7` but everything seems to be working on `alpha.8`

**Comment by fibo** [comment] 2022-10-24 10:48
@IljaDaderko done here https://github.com/fibo/hello-walletconnect/commit/531df2e4a2c3db539aa5939bcf4f83034e5a2830

I got the same result. On Desktop "connection declined" (see screenshot). On mobile: no feedback, no connection.

I will close it, thanks for the support but I do not have time to test.

**Comment by qeternity** [comment] 2022-10-24 14:00
@IljaDaderko can also confirm that accessing from localhost results in connection declined error

**Comment by IljaDaderko** [comment] 2022-10-24 14:01
@qeternity on alpha.8 / create-react-app as well?

**Comment by qeternity** [comment] 2022-10-24 14:09
yes, fresh repo
<img width="301" alt="image" src="https://user-images.githubusercontent.com/33002121/197546130-b3b44bbf-9e32-4699-a718-90eeed072493.png">

**Comment by qeternity** [comment] 2022-10-24 14:12
I am just working in a local repo at the moment, but the entire app consists of the following and to be clear, Metamask shows that I am connected.

`const App = () => {
  return (
    <>
      <ConnectButton />
      <Web3Modal config={config} />
    </>
  );
};`

**Comment by IljaDaderko** [comment] 2022-10-24 14:15
@qeternity any chance metamask remembers connection from some other web3 project you previously ran and connected with on same localhost port? Maybe that's interfering somehow with web3modal.

Could you please try adding some random port to your "start" script i.e. `PORT=3005` and check if metamask is still marked as connected / you are still getting this same error.

**Comment by qeternity** [comment] 2022-10-24 14:17
I tried changing ports and made sure to revoke previous permissions but it does not make a difference.

**Comment by IljaDaderko** [comment] 2022-10-24 14:19
Alright, ty for trying these out, I'll have to investigate.

**Comment by IljaDaderko** [comment] 2022-10-24 14:34
@qeternity doub't this will work, but just in case, does this issue happen for you in this repo?
https://github.com/IljaDaderko/cra-w3m-test

I've cleared my brosers cache / reopened it etc. but am unable to replicate in brave, chrome and firefox. Metamask always pops up for me

1. Add your project id in `App.js`
2. `npm install`

**Comment by IljaDaderko** [comment] 2022-10-24 14:46
After some more investigation, I think this happens when

1. You are already connected (web3modal + metamask are in connected state)
2. Try to connect again

Will introduce fix in next beta, perhaps to swap out connect button to pre-made disconnect one, but you should be able to fix this in the following way for now

1. Use `useAccount` hook to check if user is connected and hide connect button
2. Add `useDisconnect` hook and create your own disconnect button for now

You should be able to connect without error again once you disconnect

**Comment by fibo** [comment] 2022-10-24 21:19
@IljaDaderko the demo here is working: https://web3modal.pages.dev/

can you please share where is hosted the code for that demo and which web3modal version are they using?

**Comment by IljaDaderko** [comment] 2022-10-25 06:57
@fibo that's react example https://github.com/WalletConnect/web3modal/tree/V2/examples/react

And you can reference one here which is more streamlined https://github.com/IljaDaderko/cra-w3m-test
As I mentioned above, this issue seems to be happening when you are already connected but don't remove "Connect" button, thus allowing users to go through this flow again.

Next release will swap this button out to "Disconnect" one and latter on to a rich "Account Widget", but for now you can do that manually as shown [here](https://github.com/IljaDaderko/cra-w3m-test/blob/main/src/App.js#L20-L31) (you should be able to disconnect and then connect again as expected)

**Comment by fibo** [comment] 2022-10-25 08:09
@IljaDaderko it is working on Desktop now, with a code like this https://github.com/fibo/hello-walletconnect/blob/99382cf7da79380d6e62211d2bb5dd5222a64a1b/src/components/WalletConnectButton.js

It is not working yet on iPhone, which is the reason I am trying web3modal

<img width="695" alt="Screenshot 2022-10-25 at 10 08 34" src="https://user-images.githubusercontent.com/176730/197719112-b1a7b841-e496-4aff-9465-29fce6422daa.png">

**Comment by IljaDaderko** [comment] 2022-10-25 08:18
@fibo I assume this is on iPhone localhost through remote debugging? This one will take a bit more time to debug, looks like something from webpacks dev build is missing / not being sent over or not available with this approach. I think only workarounds atm are

1. Develop locally in mobile mode (chrome / safari etc...)
2. Set up deployments / preview deployments on providers like vercel / netlify / cloudflare etc... to test on an actual device and open web inspector for that

**Comment by fibo** [comment] 2022-10-25 08:18
ah ok, on iPhone is not my localhost so I need to run the webapp with https, see this commit https://github.com/fibo/hello-walletconnect/commit/aa527589df0d1e37aedbcb314dc2c50c858c029c


@IljaDaderko now it is working on Mobile, thanks for the support: it looks like you created your first repo on GitHub to support this issue xD

**Comment by IljaDaderko** [comment] 2022-10-25 08:21
@fibo Nice! I didn't know about that, will deff use that from now on as well for faster mobile workflow!

**Comment by fibo** [comment] 2022-10-25 08:22
@IljaDaderko if it were my project I would add this info in the docs

1. basic connect snippet (needs to handle the ConnectButton to return null once `account.isConnected`
2. HTTPS is mandatory if you run it on iPhone

Actually I am trying web3modal because there is no way right now (AFAIK) to connect wallets on mobile, other than using MetaMask browser.

**Closed by IljaDaderko** 2022-10-25 08:21 UTC
Labels: bug, v2

**Comment by IljaDaderko** [comment] 2022-10-25 08:24
100%

> basic connect snippet (needs to handle the ConnectButton to return null once account.isConnected) otherwise many other devs will get frustrated at first try.

This will be handled in next release (i.e. introduction of automatic Disconnect button), so should help others who don't use custom buttons

> HTTPS is mandatory if you run it on iPhone.

Gonna add this in as well 👍

**Comment by djaffer** [comment] 2022-11-13 08:36
Same issue. On codesandbox it doesn't work. The documentation seems to have gaps
