### ISSUE TITLE
[bug] Send transactions / tokens with v2 issue

### ISSUE THREAD

**Issue by GeekEdem** [WalletConnect/web3modal#1082] opened 2023-06-19 07:48 UTC
### Link to minimal reproducible example

https://walletconnect-check.chikhrai.xyz

### Summary

Hello. Have some issues with try send ETH/tokens with v2 when try to interact with TrustWallet.
And on iOS not work sign message.
Same code work correct with metamask on v1 on Android. On iOS it not create transactions...
On Android sign message with v2 with TrustWallet work correct too.

Create some demo-stand to reproduce full cicle with v1/v2 modal with this wallets.

Full code can be found here: https://github.com/YuriiChikhrai/walletconnect_check

### List of related npm package versions

 - `wagmi` / `@wagmi/core` v1.3.4
 - `viem` v1.2.9
 - `@web3modal/ethereum` / `@web3modal/react` v2.6.2
 - `react` v16.14.0
 - `webpack` v5.87.0
 - `typescript` v5.1.6

**Comment by 0xAsimetriq** [comment] 2023-07-01 05:53
Repro you provided has a lot going on there, could you post relevant code snippets and try to upgrade to latest modal version to see if issue is solved. Make sure to update to latest wallet versions as well, as both metamask and trust had few known issues that were resolved recently.

**Comment by GeekEdem** [comment] 2023-07-03 10:38
@0xAsimetriq Thanks for your response.
Yep, where is a lot of going on there, because is actual real use-case example :)

I remove code of chosing version (because is only v2 now), upgrade all walletconnect/wagmi/viem dependencies to latest versions (and mobile wallets app too). 

Results: 
 - Metamask works correct
 - TrustWallet works correct with connect/sign/send tokens, when try send ETH - error 
 
 ```
TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:   0x...
  to:     0x...
  value:  0.00000001 ETH
  gas:    100000
 ```
 
 And 
 ```
 {context: 'client'} 'Unknown method(s) requested'
 ```
 
 Thanks.

**Comment by 0xAsimetriq** [comment] 2023-07-03 10:51
Does the error state name of the method that is failing? i.e. which rpc method exactly is failing and does Trust wallet support it? Does this work with other wallets i.e. Zerion / Rainbow?

**Comment by meri-maki** [comment] 2023-07-08 15:56
@0xAsimetriq I have a similar issue when trying to send transactions when connected to Zerion and TrustWallet (via WalletConnect). Rainbow wallet and UniSwap works fine
I opened an issue in wagmi since I'm using their config but no solution yet

Here is the link to the issue for reference: https://github.com/wagmi-dev/wagmi/issues/2713

I'm using latest versions of react/wagmi/viem
here is the build with error

https://github.com/meri-maki/wagmi-issue
https://wagmi-issue.vercel.app/

To reproduce:

Connect to Zerion/TrustWallet wallet via WalletConnect (except for metamask)
Try sending transaction
Get
```
TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:   0x568A33aA237fFc284FF584A3BAB17A44FAeF4054
  to:     0xE8078B5198E572Be8D8D412511d48b7D0f5E9a1c
  value:  0.000001 ETH
  gas:    104799
  ```

**Comment by meri-maki** [comment] 2023-07-08 19:59
Found out that sendingTransaction only works in this example: https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2

It looks really complex.. could you please advise on which logic to add to the app so transactions work? i suppose the key is to add JsonRpcContext?

**Comment by TEE2DWHY** [comment] 2023-07-12 18:21
hello @meri-maki . I'm also experiencing the same issue on trust wallet but it works on safepal and metmask. Any solution??

**Comment by theblockjet** [comment] 2023-07-16 10:05
same issue. any solution?

**Comment by 0xAsimetriq** [comment] 2023-07-16 10:14
At this point all we know is that it's either wallet not parsing tx data correctly or tx data being incorrect. There is also a chance that wallet doesn't support method used to send transaction, however as far as I know trust should have no problem.

**Comment by TEE2DWHY** [comment] 2023-07-16 10:16
I think generally trust wallet  does not work with WAGMI sendTransaction. Cause I even tried on their official website. Is there any available codebase using etheruemProvider to initiate transaction?? @0xAsimetriq

**Comment by meri-maki** [comment] 2023-07-16 10:25
@TEE2DWHY Hi! I had a backup with web3js logic (no wagmi/viem) that works with almost all wallets (including trust/zerion)
"web3": "^1.10.0",
"web3-eth": "^1.10.0"

But wagmi hooks provide much better user and programming experience + it's much faster that old web3js
I sincerely hope that the issue with trust would be resolved (also it doesn't want to connect via walletconnect in Trust Wallet Browser) and I could use it in my production build

**Comment by TEE2DWHY** [comment] 2023-07-16 10:27
@meri-maki . Oh wow. Amazing. I also hope wagmi issue is resolved also. Could you drop link to your code base for the web3js?. I’ll really appreciate 🙏🏼

**Comment by 0xAsimetriq** [comment] 2023-07-16 10:28
@TEE2DWHY In this case I'm not sure if we can help in terms of web3modal repo, this sounds like an issue on trust wallet side. I know viem is using approaches that might differ from how ethers did it back in v5, could be the case where trust is not compliant with latest specs and only handles legacy stuff, not sure.

Will be closing this issue for now, as there is nothing actionable for us here, will reach out to wagmi guys and ask if they know anything about this.

**Closed by 0xAsimetriq** 2023-07-16 10:28 UTC
Labels: needs feedback

**Comment by TEE2DWHY** [comment] 2023-07-16 10:30
@0xAsimetriq. Thank you. @meri-maki. I’ll really appreciate if you could drop link to the web3.js back up. Thank you

**Comment by itsinayats** [comment] 2023-07-16 12:01
> @TEE2DWHY Hi! I had a backup with web3js logic (no wagmi/viem) that works with almost all wallets (including trust/zerion) "web3": "^1.10.0", "web3-eth": "^1.10.0"
> 
> But wagmi hooks provide much better user and programming experience + it's much faster that old web3js I sincerely hope that the issue with trust would be resolved (also it doesn't want to connect via walletconnect in Trust Wallet Browser) and I could use it in my production build

could you explain how you solved this issue?

**Comment by TEE2DWHY** [comment] 2023-07-16 12:46
Hello @itsinayats. It was @meri-maki who got the solution not me. I’m still waiting for the  response also.

**Comment by meri-maki** [comment] 2023-07-16 13:15
Hi @TEE2DWHY @itsinayats i sent you both an email with code, can’t share the repo of my organisation

**Comment by itsinayats** [comment] 2023-07-16 14:02
> Hi @TEE2DWHY @itsinayats i sent you both an email with code, can’t share the repo of my organisation

Thank you

**Comment by meri-maki** [comment] 2023-07-17 07:16
Hi @TEE2DWHY @itsinayats web3 and web3-eth could be updated to latest version, please see this issue for change in logic that should be made
https://github.com/web3/web3.js/issues/6249

tested it, works fine!

**Comment by GeekEdem** [comment] 2023-07-17 10:15
Em... I doesn't know how it can be, but solution is add `data: "0x"` to `usePrepareSendTransaction`:
```
const { config } = usePrepareSendTransaction({
    to,
    value,
    chainId,
    gas: BigInt(10000),
    
    data: "0x",
});
```

Solution take from here: https://github.com/wagmi-dev/wagmi/issues/2161

**Comment by itsinayats** [comment] 2023-07-17 10:40
> Em... I doesn't know how it can be, but solution is add `data: "0x"` to `usePrepareSendTransaction`:
> 
> ```
> const { config } = usePrepareSendTransaction({
>     to,
>     value,
>     chainId,
>     gas: BigInt(10000),
>     
>     data: "0x",
> });
> ```
> 
> Solution take from here: [wagmi-dev/wagmi#2161](https://github.com/wagmi-dev/wagmi/issues/2161)

I just tried it. 
It worked very well. Finally got some workaround.
Thak you so much

**Comment by ismoli** [comment] 2023-09-20 12:37
I also have this issue with TW. Workaround indeed works, however TrustWallet brings "Smart contract call" titled window (instead of a simple send) alongside with warning note that site will be able to access funds. I personally would not confirm such a call cause it does look suspicious. not ideal and frightens users!

**Comment by cesar4design** [comment] 2024-03-28 09:42
> data: "0x",

Great, this work for native token tranfer using usePrepareSendTransaction,
but for call any other contract function using usePrepareContractWrite, you know how to fix?

**Comment by NimaCharkhgard** [comment] 2024-03-30 20:31
@itsinayats Thanks for your help...!!!
works great
