### ISSUE TITLE
webpack5 failed

### ISSUE THREAD

**Issue by balya7777** [WalletConnect/web3modal#570] opened 2022-09-06 03:52 UTC
I get the error when `npm install --save @walletconnect/web3-provider`.

`npm i stream-browserify url assert util stream-http https-browserify os-browserify buffer` may be the solution .

![image](https://user-images.githubusercontent.com/38807330/188543724-0532be88-a58e-4ff9-99aa-98c15e6f2d86.png)

![image](https://user-images.githubusercontent.com/38807330/188543788-a663078b-bb93-42dd-80eb-48abb9474e16.png)

How do you think about it?

**Comment by hackyguru** [comment] 2022-09-16 16:36
Not sure what the problem is. Can you show us the error log?

**Comment by 0xAsimetriq** [comment] 2023-01-21 16:40
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Closed by 0xAsimetriq** 2023-01-21 16:40 UTC
Labels: v1
