### ISSUE TITLE
[bug] Incorrect blockchain: arbitrum-mainnet.gateway.pokt.network

### ISSUE THREAD

**Issue by reupcash** [WalletConnect/web3modal#1078] opened 2023-06-18 15:49 UTC
### Link to minimal reproducible example

https://reup.cash

### Summary

RPC calls are being made to: `https://rpc.walletconnect.com/v1/?chainId=eip155:42161&projectId=xxx`

75% of them get this error message:

```
{
    "jsonrpc": "2.0",
    "id": 6,
    "error": {
        "message": "Incorrect blockchain: arbitrum-mainnet.gateway.pokt.network",
        "code": -32057
    }
}
```

Retrying requests occasionally works. The error is transient, but it's making Arbitrum apps nearly completely unusable.

To me, it looks like walletconnect is using pokt.network and hitting a bad node.

### List of related npm package versions

    "@web3modal/ethereum": "^2.4.7",
    "@web3modal/react": "^2.4.7",
    "@wagmi/chains": "^1.1.1",
    "@wagmi/core": "^1.2.0",
    "abitype": "^0.8.10",
    "viem": "^1.0.7",
    "wagmi": "^1.2.0"

**Comment by 0xAsimetriq** [comment] 2023-06-18 18:18
Closing as a duplicate of https://github.com/orgs/WalletConnect/discussions/2674 (our rpc team is looking into the issue as per reply there).

**Closed by 0xAsimetriq** 2023-06-18 18:18 UTC
Labels: bug, P0
