### ISSUE TITLE
[bug] Page contents are shifting when modal is opened [V3]

### ISSUE THREAD

**Issue by pauldemarco** [WalletConnect/web3modal#1343] opened 2023-09-19 18:31 UTC
### Link to minimal reproducible example

https://web3modal.com/

### Summary

1. Open the landing page for v3 (https://web3modal.com/)
2. Click the "CONNECT WALLET" button at the top right
3. Notice how the page contents shift when the modal opens.

I am testing with a Chrome browser on the desktop.

### List of related npm package versions

3.0.0-beta.3

**Comment by skusez** [comment] 2023-09-19 23:50
+1, the modal pushes components to the top of the page in my application

**Comment by skusez** [comment] 2023-09-20 00:48
it seems walletconnect styles are applied to the html tag, when I moved my css styles off the html tag it fixed the problem for me

**Comment by 0xAsimetriq** [comment] 2023-09-20 05:38
Replicated, will be fixed in this release. To give more context when modal get's open we prevent page scrolling as it can lead to a lot of issues, especially on mobile (common practice with modals). Shift is caused by adjusting gutter of scroll-bar incorrectly.

**Comment by 0xAsimetriq** [comment] 2023-09-20 13:03
released in beta.4

**Closed by 0xAsimetriq** 2023-09-20 13:03 UTC
Labels: bug, v3

**Comment by pauldemarco** [comment] 2023-09-20 22:57
This still happening for anyone else or just me?

Page contents are still shifting on this website: https://web3modal.com/

@0xAsimetriq shall we re-open?

**Comment by 0xAsimetriq** [comment] 2023-09-21 05:32
@pauldemarco Different kind of shift now, if your browser hides the scrollbar when scroll is dissabled and doesn't compensate for that, you'll see content shift. For this one, we can't fo anything. One that was removed is related to "scroll-gutter" css rule that we set before
