### ISSUE TITLE
Safe error ethers v5

### ISSUE THREAD

**Issue by CjoyHome** [WalletConnect/web3modal#1552] opened 2023-12-08 09:13 UTC
### Summary

wallet: https://app.safe.global
version：
```
  "@walletconnect/modal": "^2.6.2",
    "@web3modal/ethers5": "^3.4.0",
    "ethers": "^5.7.2"
```
![image](https://github.com/WalletConnect/web3modal/assets/26813427/94230dac-9ddd-4151-b5be-9e2efd42b1b5)

![image](https://github.com/WalletConnect/web3modal/assets/26813427/cca74002-2571-46d3-82d5-944df25fd1bc)

I need to connect to the safe wallet. I can't find the relevant method of configuring namespaces in the web3modal tutorial. I hope I can get help.

### Link to the related docs page

https://docs.walletconnect.com/web3modal/nextjs/about

**Comment by CjoyHome** [comment] 2023-12-08 11:52
Could you please tell me whether I haven't configured something or am I configuring something wrong? I have the above problem now.
My code:
```

import { createWeb3Modal, defaultConfig } from '@web3modal/ethers5/react'
// 1. Get projectId at https://cloud.walletconnect.com
const projectId = 'xxx'
// 2. Set chains
const mainnet = {
    chainId: 1,
    name: 'Ethereum',
    currency: 'ETH',
    explorerUrl: 'https://etherscan.io',
    rpcUrl: process.env.NEXT_PUBLIC_CRYPTO_JSONRPCPROVIDER_ETH
}

const metadata = {
    name: 'xxx',
    description: '',
    url: 'xxx',
    icons: ['xxxx']
}

createWeb3Modal({
    ethersConfig: defaultConfig({
        metadata,
        rpcUrl: process.env.NEXT_PUBLIC_CRYPTO_JSONRPCPROVIDER_ETH
    }),

    chains: [mainnet],
    projectId
})

  
export function Web3ModalProvider({ children }) {
    return children;
}

```

**Comment by CjoyHome** [comment] 2023-12-08 12:02
Yes,My dapp was upgraded from v1. Will this monitoring method affect it?

```
if (isConnected && walletProvider?.on) {
            ethersProvider = new ethers.providers.Web3Provider(walletProvider)

            const handleBlockChange = (blockNumber) => {
                walletPreviousBlockNumber = walletLatestBlockNumber;
                walletLatestBlockNumber = blockNumber;
            }
            // disconnectWalletIfBlockError()
            const handleAccountsChanged = (accounts) => {
                console.log(accounts)
                window.location.reload(false);
            }

            const handleChainChanged = (chainId) => {
                window.location.reload(false);
            }

            const handleDisconnect = (error) => {
                walletConnectedAddress = ''
                window.location.reload(false);
            }

            // Subscribe to provider connection
            // providerTmp.on("connect", (info: { chainId }) => {
            //     console.log("connect");
            //     console.log(info);

            //     checkConnection();
            // });

            ethersProvider.on('block', handleBlockChange);
            // Subscribe to accounts change
            walletProvider.on("accountsChanged", handleAccountsChanged);
            // Subscribe to chainId change
            walletProvider.on("chainChanged", handleChainChanged);
            // Subscribe to provider disconnection
            walletProvider.on("disconnect", handleDisconnect)
            return () => {
                if (walletProvider.removeListener) {
                    walletProvider.removeListener("accountsChanged", handleAccountsChanged);
                    walletProvider.removeListener("chainChanged", handleChainChanged);
                    walletProvider.removeListener("disconnect", handleDisconnect);
                    ethersProvider.removeListener("block", handleBlockChange)
                }
            }
        }
```

**Comment by glitch-txs** [comment] 2023-12-08 12:03
could you try connecting here
https://lab.web3modal.com/library/ethers-siwe/

**Comment by CjoyHome** [comment] 2023-12-08 12:05
[](https://web3modal.com/ )
The test on this official website is fine

**Comment by glitch-txs** [comment] 2023-12-08 12:10
no, that one uses wagmi, could test the one I sent?

**Comment by CjoyHome** [comment] 2023-12-08 12:14
Tried it, same problem occurs

**Comment by glitch-txs** [comment] 2023-12-08 12:19
thanks, we'll look into this

**Comment by glitch-txs** [comment] 2023-12-08 14:40
hi could you try again?

**Comment by CjoyHome** [comment] 2023-12-08 15:06
Just tried it, still the same error message.

**Comment by glitch-txs** [comment] 2023-12-08 16:23
The issue is on Safe side, I've sent them a message about this, hopefully it'll get fixed soon.

**Comment by CjoyHome** [comment] 2023-12-08 16:25
Okay，thank you so much

**Comment by glitch-txs** [comment] 2023-12-09 11:04
Hi @CjoyHome they will release a fix soon, I'll be closing this as it's not related to Web3Modal. You can follow the issue in Safe repo :)

https://github.com/safe-global/safe-wallet-web/issues/2946

**Closed** 2023-12-09 11:05 UTC
Labels: bug, ethers5

**Comment by CjoyHome** [comment] 2023-12-22 06:35
I tested it today and no problem occurred. Thank you for following up on this issue.
