### ISSUE TITLE
missing: typescript example

### ISSUE THREAD

**Issue by TiltUp-Rad** [WalletConnect/web3modal#1258] opened 2023-08-07 10:38 UTC
I wanted to play around with web3modal in typescript.

I followed [the official guide](https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/installation), but was unable to finish my setup due to dependency problems

to reproduce run the following:

1. `npx create-react-app web3modal --template typescript`
2. `cd web3modal `
3. `npm install @web3modal/ethereum @web3modal/react wagmi viem`
[initial problem screenshot](https://i.stack.imgur.com/3XKXS.png)

so I tried to solve it:

4. `npm i typescript@^5 (which results in warning shown below)`
[warnings screenshot](https://i.stack.imgur.com/XhH5L.png)

5. `npm install @web3modal/ethereum @web3modal/react wagmi viem`
which results in more errors now, screenshot truncated [more errors screenshot](https://i.stack.imgur.com/aOk86.png)

I tried searching for a version of web3modal that uses typescript ^4, but after going down to 2.3.0 - it still sits at 5.0.4.

so my question is:
is there any react/typescript example that uses up-to-date versions of web3modal? and if not - what are the versions of web3modal/wagmi/viem that I can downgrade to to still use typescript 4.9.5?

I didn't know where to put it, so feel free to remove the unnecessary ones
first published here: https://stackoverflow.com/questions/76835789/a-working-example-of-web3modal-with-typescript-5
also posted here: https://github.com/WalletConnect/web3modal-examples/issues/41

**Comment by 0xAsimetriq** [comment] 2023-08-07 14:47
Closing as duplicate of https://github.com/WalletConnect/web3modal-examples/issues/41

**Closed** 2023-08-07 14:48 UTC
