### ISSUE TITLE
Previous events for contract

### ISSUE THREAD

**Issue by asimaranov** [WalletConnect/web3modal#697] opened 2022-11-11 12:11 UTC
It seems that useContractEvent returns only new events that accrued since frontend launched. Is there way to get the past events? Something like getPastEvents from web3js. Maybe there is a way to get web3js from modal window provider to call getPastEvents? How can I get the past events?

**Comment by IljaDaderko** [comment] 2022-11-15 07:34
Will look into this, but closing this issue as a duplicate of https://github.com/WalletConnect/web3modal/issues/646

**Closed by IljaDaderko** 2022-11-15 07:34 UTC
Labels: feature-request, v2
