### ISSUE TITLE
Set ZIndex for the modal

### ISSUE THREAD

**Issue by fsobh** [WalletConnect/web3modal#332] opened 2021-10-05 18:23 UTC
Im not able to control zindex of modal and its causing it to be last layered item (stopping me from clicking button)

**Comment by fsobh** [comment] 2021-12-09 19:55
> 

im still facing this issue

**Comment by chadyj** [comment] 2022-12-14 11:56
Dupe of https://github.com/WalletConnect/web3modal/issues/332

**Comment by chadyj** [comment] 2022-12-14 11:57
Dupe of https://github.com/WalletConnect/web3modal/issues/165

**Closed by chadyj** 2022-12-14 11:57 UTC
Labels: v1
