### ISSUE TITLE
[bug] When signMessage on mobile didnt redirect to WalletApp

### ISSUE THREAD

**Issue by luisdeka** [WalletConnect/web3modal#965] opened 2023-03-30 23:07 UTC
### Link to minimal reproducible example

https://stackblitz.com/edit/viem-getting-started-a3ekcn?file=index.tsx

### Summary

In mobile, when a user click some action like "signMessage" has to open the walletApp, at the moment that is not happening, not working on v1, not working on v2.

At the moment a temporal solution is before user do signMessage open the uri.

### List of related npm package versions

I have tested with v1 and v2 implementations (ethers, web3modal/html, wagmi) and (web3modal/standalone, viem, ethereumProvider), no one works.

Note: i am using Vue.js not react, but the example have the same behavior.

**Comment by 0xAsimetriq** [comment] 2023-03-31 10:36
Can you reproduce on https://lab.web3modal.com ?
It opens up metamask, trust, tainbow and zerion fine for me.

You can connect to one of the examples that use wagmi, they will display "sign message" action after connecting.

**Comment by luisdeka** [comment] 2023-03-31 19:41
> Can you reproduce on https://lab.web3modal.com ? It opens up metamask, trust, tainbow and zerion fine for me.
> 
> You can connect to one of the examples that use wagmi, they will display "sign message" action after connecting.

Yeah, lab.webmodal works, but it uses react-ui, without the ui didnt work.

This example didnt open wallet when signMessage and my implementations didnt open wallet if i dont save

**Comment by luisdeka** [comment] 2023-03-31 19:42
th

**Comment by luisdeka** [comment] 2023-03-31 19:56
Maybe wagmi fix it in some way that @wagmi/core didnt? I have check @web3modal/react and the laboratory and i didnt see nothing special, the only thing is you use react and can use wagmi, so maybe wagmi is hidding the problem.

**Comment by miguelaeh** [comment] 2023-04-02 10:21
I can confirm what @luisdeka is reporting. I tried to make it work around 3 weeks ago, and I ended up showing "Open your wallet" to the user.
The behavior I found is that the "connect" action redirects fine, but the "signMessage" doesn't. Also, this produces that the user has to have the wallet open before using the signMessage, if not, the sign request never arrives at the wallet, even if the user manually opens it after the sign request.
I tested web3modal/react, even though I ended up using the standalone.
I guess the behavior has sense when you are using a QR code to connect a mobile wallet to a desktop dapp, but for mobile to mobile doesn't seem to be creating a good UX.

Hope this help, let me know if I can provide more info.

**Comment by 0xAsimetriq** [comment] 2023-04-02 12:00
@miguelmota Can you provide reproduction code for your use case as well please. With luisdeka's situation, there is possibility that redirect doesn't happen due to using viem, something I need to look into. Are you also using something like that or have a different setup?

**Comment by da748** [comment] 2023-04-02 13:30
It the same thing here, the mobile seems to be lifeless after connection with the table view, till can't open on his own

**Comment by 0xAsimetriq** [comment] 2023-04-03 05:57
Will look into this, but so far wasn't able to re-produce. Would appreciate more reproduction code that's non viem to figure out where the issue could be.

**Comment by luisdeka** [comment] 2023-04-03 09:36
With Android.

This example reproduce the problem.
https://stackblitz.com/edit/viem-getting-started-a3ekcn?file=index.tsx

I have the problem with viem and with @wagmi/core, with both of them.

And this example is a reproduction too.
https://wagmi.sh/examples/sign-message

**Comment by miguelaeh** [comment] 2023-04-03 10:48
>Can you provide reproduction code for your use case as well please. With luisdeka's situation, there is possibility that redirect doesn't happen due to using viem, something I need to look into. Are you also using something like that or have a different setup?

I am not using anything special. In my case, I am just building a `tx` with ethers and signing like:
```
    const result = await signClient.request({
        topic,
        chainId,
        request: {
          method: "eth_sendTransaction",
          params: [tx],
        },
    });
```

**Comment by 0xAsimetriq** [comment] 2023-06-13 08:38
This is now fixed in latest version of sign-client package and all upstream libraries that use it.

**Closed by 0xAsimetriq** 2023-06-13 08:38 UTC
Labels: needs feedback
