### ISSUE TITLE
QR code stops working after some time

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3modal#733] opened 2022-11-25 07:28 UTC
**Is your feature request related to a problem? Please describe.**
Some users and wallets report that the QR code stops working after 30 seconds or so.
Some users think the wallet or dapp is broken instead of reloading the page.

**Describe the solution you'd like**
 Every time a pairing fails or expires you just automatically refresh the qrcode

**Describe alternatives you've considered**
Show the user how much time is left by adding a timer/timeout counter below the QR code like TOTP codes run

**Comment by IljaDaderko** [comment] 2022-11-25 07:30
Closing as a duplicate of a task in https://github.com/WalletConnect/web3modal/issues/585

**Closed** 2022-11-25 07:34 UTC
Labels: v2
