### ISSUE TITLE
When Metamask is locked, by calling connect function, the Metamask window won't pop up.

### ISSUE THREAD

**Issue by y0unghe** [WalletConnect/web3modal#454] opened 2022-04-07 10:37 UTC
How to open the Metamsk window so the user can enter the password to unlock the wallet when Metamsk is locked? 

```
let web3Modal
if (typeof window !== 'undefined') {
    web3Modal = new Web3Modal({
        network: 'maticmum', // optional
        cacheProvider: true,
        providerOptions, // required
    })

    await web3Modal.connect()
}
```

**Comment by nftchance** [comment] 2022-06-01 20:56
Do you have information on how to reproduce this?

**Comment by 0xAsimetriq** [comment] 2023-01-21 16:39
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Closed by 0xAsimetriq** 2023-01-21 16:39 UTC
Labels: v1
