### ISSUE TITLE
Network in modal not synchronized with connected wallet's network

### ISSUE THREAD

**Issue by foxfriends** [WalletConnect/web3modal#815] opened 2023-01-09 21:49 UTC
**Describe the bug**
The network (shown in the modal) does not seem to be synced up with Metamask (or other wallet UI) after page reloads or internal routing changes

**SDK Version**
 - Version: 2.0.0-rc.2 + whatever is currently on the try-it-out

**To Reproduce**
1. Go to https://web3modal.com/try-it-out
2. Connect a Metamask/Brave wallet (maybe others too)
3. Change the network to anything but Ethereum (e.g. Polygon)
4. Reload the page, or trigger an internal route change (e.g. click on "Introduction" in the left nav)
6. Navigate back to the try it out page, see it showing Polygon balance but with network as Ethereum

**Expected behavior**
The network on the modal should always be synchronized with the wallet selected in the Metamask/other wallet UI.

**Screenshots**
![Screenshot 2023-01-09 at 4 46 14 PM](https://user-images.githubusercontent.com/6126521/211414765-f434e85f-9c22-4ac7-bf50-6751044ce2e6.png)

**Desktop (please complete the following information):**
 - OS: Mac (Ventura 13.1)
 - Browser: tested Firefox (108.0.2) and Brave (1.46.153)

**Additional context**

**Comment by 0xAsimetriq** [comment] 2023-01-09 22:23
Replicated, gonna look into this 👍

**Comment by 0xAsimetriq** [comment] 2023-01-10 12:44
Can you replicate this issue on https://rc-3.web3modal-dev.pages.dev I think it is something with the setup we have going in web3modal.com specifically (being reworked).

If issue is not present in preview url above, we can safely close this ticket.

**Comment by foxfriends** [comment] 2023-01-10 14:42
Yeah I can't seem to reproduce it on that page.

Do you know what exactly it is that's causing that issue on the original page? I am seeing it on my own site as well, so would like to know how to avoid it.

**Comment by 0xAsimetriq** [comment] 2023-01-10 14:45
I'll let you know once I figure out the cause on web3modal.com 👍

**Comment by foxfriends** [comment] 2023-01-17 21:51
I pulled rc3 into my project and this issue is gone now

**Comment by foxfriends** [comment] 2023-01-26 16:55
As a workaround, I wrapped `Web3Modal` component in `React.memo` and it's working now. Not sure if that will cause me any problems down the line though...

**Closed** 2023-02-02 10:58 UTC
Labels: v2, needs feedback
