### ISSUE TITLE
[bug] Issue with Labolatory example on Safari

### ISSUE THREAD

**Issue by o-tsaruk** [WalletConnect/web3modal#2156] opened 2024-04-15 10:02 UTC
### Link to minimal reproducible example

https://lab.web3modal.com/library/ethers/

### Summary

Page: Ethers - Default
Device: iPhone (13)
Browser: Safari

Steps:
1. Open the page using Safari browser.
2. Click the "Connect Wallet" button
3. Choose any popular wallet (Metamask/Trust Wallet/ etc.)

Expected behavior: after choosing a wallet web app redirects the user to the wallet app.

Current behavior: user gets "Safari cannot open the page because the address is invalid." message. I've tested it on several iPhones.

Thank you for any answer =)

### List of related npm package versions

[Laboratory package.json](https://github.com/WalletConnect/web3modal/blob/V4/apps/laboratory/package.json)

**Comment by Sam-Newman** [comment] 2024-05-30 10:18
Hi -  thanks for raising this. I was not able to reproduce it so I will close it. Please re-open if it persists

**Closed** 2024-05-30 10:19 UTC
Labels: bug, needs review
