### ISSUE TITLE
[bug] : Add web3auth to providerOptions, but it doesn't work and doesn't show up in Web3Modal

### ISSUE THREAD

**Issue by LiJinLan** [WalletConnect/web3modal#538] opened 2022-07-22 06:33 UTC
Add web3auth:  

```
const providerOptions = {
      walletconnect: {
        package: WalletConnect,
        options: {
          infuraId
        }
      },
      web3auth: {
        package: Web3Auth,
        options: {
          infuraId: 'BEwLNa-8qQ8XTTxUJz_arZFkPwarQ9kzaC_Cfh3FocQCUT2LCJeaH5r8Kjku82jWYMQTL5al8Ze4VDI91DotwOM',
        }
      },
      torus: {
        package: Torus, // required
        apiKey: 'BGYsGUh8Lp36FKNM2guCMYq9HBwe_vzb2QyYLu4d_eAmfka4FikmQ1QqJ_53H9xV0ujxLq3QKgZyfc9DjpsgIus',
        options: {
          apiKey: 'BGYsGUh8Lp36FKNM2guCMYq9HBwe_vzb2QyYLu4d_eAmfka4FikmQ1QqJ_53H9xV0ujxLq3QKgZyfc9DjpsgIus',
          networkParams: {
            chainId: 56, // optional
          },
        }
      }
    };
```

The result is this, Web3Auth doesn't show up in Web3Modal

![image](https://user-images.githubusercontent.com/53366656/180377650-62abfa2d-c406-416d-84c0-46edf916dc3f.png)

**Comment by pauljulianheise** [comment] 2022-08-15 00:50
I can confirm this bug, doesn't work for me either

**Comment by htcarr3** [comment] 2022-09-02 18:59
Same issue for me

**Comment by htcarr3** [comment] 2022-09-06 18:26
@LiJinLan @pauljulianheise , update to 1.9.9, this just wasnt updated until the last version. Should work now

**Comment by 0xAsimetriq** [comment] 2023-01-21 16:41
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Closed by 0xAsimetriq** 2023-01-21 16:41 UTC
Labels: v1
