### ISSUE TITLE
[feature] Multilingual Support

### ISSUE THREAD

**Issue by fffedor** [WalletConnect/web3modal#1094] opened 2023-06-23 15:28 UTC
### What problem does this new feature solve?

Greetings.
Firstly, thank you for the excellent work. I have a need to use web3modal in several languages, I realise that there is very little vocabulary there, but nevertheless.

Is this a possibility now or is it planned in the future?

### Describe the solution you'd like

Additional option

**Comment by 0xAsimetriq** [comment] 2023-06-24 05:18
Duplicate of https://github.com/WalletConnect/web3modal/issues/627

**Closed by 0xAsimetriq** 2023-06-24 05:18 UTC
Labels: feature-request, needs review
