### ISSUE TITLE
Clicking on MetaMask on iOS opens the App Store for the app, instead of opening the app itself

### ISSUE THREAD

**Issue by teejteej** [WalletConnect/web3modal#395] opened 2022-01-28 09:16 UTC
When clicking on the MetaMask icon in web3modal, for some devices it opens the App Store page, even though the app is already installed. So clicking on "Open" from the App Store then, doesn't bring the user in the "connect wallet" flow.

This only happens on a specific iOS devices (latest iOS though), while it works fine on others.

Any idea what it could be?

**Comment by mhammonds** [comment] 2022-03-09 20:34
@teejteej We are experiencing the same issue on one of my projects. Did you ever find a resolution to this?

**Comment by dcutugno** [comment] 2022-04-07 10:22
just updated MM on iOS and now have this issue as well, any info on how to resolve this?

**Comment by ansonkao** [comment] 2022-04-09 15:32
Confirmed that uninstalling and re-installing MetaMask resolves the issue. Definitely still need an automatic solution for users though...

**Comment by 0xAsimetriq** [comment] 2023-01-21 16:35
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Closed by 0xAsimetriq** 2023-01-21 16:35 UTC
Labels: v1
