### ISSUE TITLE
Unable to monitor the connection status of websocket

### ISSUE THREAD

**Issue by vic-x** [WalletConnect/web3modal#1209] opened 2023-07-17 11:14 UTC
### Link to minimal reproducible example

https://web3modal.com/ 

### Summary

<img width="928" alt="image" src="https://github.com/WalletConnect/web3modal/assets/36296927/cbb12a87-448d-486c-b7a5-096999b89dff">
<img width="803" alt="image" src="https://github.com/WalletConnect/web3modal/assets/36296927/be06de70-00a1-4867-baf9-3fc26dc36894">

Open it on the official website, the network is adjusted to slow speed, or it is closed, and the modal cannot be opened

to get the connection status of wss, but there is no way

Error: Socket stalled when trying to connect to

### List of related npm package versions

"@wagmi/core": "^1.3.7",
    "@web3modal/ethereum": "^2.7.0",
    "@web3modal/html": "^2.7.0",

**Comment by 0xAsimetriq** [comment] 2023-07-17 13:29
Duplicate of https://github.com/WalletConnect/web3modal/issues/1026 We are working on this on a sub-dependency level. But without network connection modal will not be able to open due to missing data and will continue to retry until network is available. You can await modal's `.open()` call and decide to error on your own after x amount of time

**Closed by 0xAsimetriq** 2023-07-17 13:29 UTC
Labels: bug, needs review
