### ISSUE TITLE
[bug] - Ethers - Networks issues

### ISSUE THREAD

**Issue by glitch-txs** [WalletConnect/web3modal#1526] opened 2023-12-01 16:35 UTC
### Link to minimal reproducible example

https://lab.web3modal.com/library/ethers/

### Summary

1. When I'm connected if the chain I want to switch to is not registered in my wallet (it used to throw an error), now it will switch in the dapp but there are no request in the wallet.
Expected behaviour:
the modal should can switchNetwork method
if it fails it should fallback into addNetwork method
then trigget switchNetwork again

2. When I use the Network button to connect it should ask me to switch to that chain after connecting, here I select polygon while my wallet is on Arbitrum, but after connecting it doesn't ask me to switch to Polygon

### List of related npm package versions

latest

**Comment by svenvoskamp** [comment] 2023-12-14 10:48
@glitch-txs Closing this one for now as I'm not able to reproduce.

**Comment by glitch-txs** [comment] 2023-12-15 15:30
I updated the description (copy/paste from slack) with the current behaviour, I also added video demos in slack 👍

**Closed** 2024-01-02 09:05 UTC
Labels: bug, ethers5, ethers
