### ISSUE TITLE
Wallet connect on TrustWallet (iOS) is not connecting

### ISSUE THREAD

**Issue by mashup-purveyor** [WalletConnect/web3modal#307] opened 2021-08-07 07:14 UTC
**Device:** TrustWallet on iOS, version 6.2.
**How to reproduce:** Install TrustWallet, attempt to join via the test website: https://web3modal.com/.
**Expected result:** Wallet connects to the dAPP.
**Actual result:** No connection is establish, and TrustWallet returns "An unknown error occurred".

The console and network reporting to their bridge is not providing any details. Apparently WalletConnect made some form of update recently. I am on the road and cannot check right now, however if someone finds some details or has sorted this out, the help is appreciated.

**Comment by dpentajeu** [comment] 2021-08-18 10:39
Same issue encountered. Using latest trust wallet's wallet connect scan the QR, fail to connect. Appreciate if someone can share how to resolve this as well.

**Comment by kelber6** [comment] 2021-08-30 14:37
Having issues with your wallet? submit a compliant ticket directly to the Trust Wallet customer support for assistance and clarification.



https://forms.gle/9CcSSGK9MyX8RjaW9

**Comment by gruvin** [comment] 2021-09-10 04:39
Exact same symptom and method to reproduce as OP.
Tried deleting Trust app and reinstalling with a fresh new wallet. No joy.

iOS 14.7.1
TrustWallet **v6.4** (OP using 6.2)

**Comment by kelber6** [comment] 2021-09-10 05:32
Having issues with your wallet? submit a compliant ticket directly to the
Trust Wallet customer support for assistance and clarification.

https://forms.gle/9CcSSGK9MyX8RjaW9

**Comment by gruvin** [comment] 2021-09-10 05:40
> Having issues with your wallet? submit a compliant ticket directly to the Trust Wallet customer support for assistance and clarification.

FUCK OFF ASSHOLE SCAMMER

**Comment by kelber6** [comment] 2021-09-10 05:42
You're not serious

**Comment by gruvin** [comment] 2021-09-10 10:44
> You're not serious
Aren't I? Anyone and _everyone_ posting random links _anywhere_ to "help" for anything relating to crypto is OBVIOUSLY scamming people. I just felt like yelling it out for once is all. If you are not a scammer, then dude, you better catch up 'cause you're gonna get your ass banned from everywhere.

**Comment by kelber6** [comment] 2021-09-10 10:52
You're a fool

**Comment by gruvin** [comment] 2021-09-10 20:12
If you say so scammer.

**Comment by Marcellsantoso** [comment] 2021-09-12 02:45
> Same issue encountered. Using latest trust wallet's wallet connect scan the QR, fail to connect. Appreciate if someone can share how to resolve this as well.

@pedrouid help us with this issue please..

**Comment by jedhavel** [comment] 2022-05-06 02:40
Is there a fix for this? A work around?

**Comment by 0xAsimetriq** [comment] 2023-01-21 15:20
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Closed by 0xAsimetriq** 2023-01-21 15:20 UTC
Labels: v1
