### ISSUE TITLE
Improvement: Localization 

### ISSUE THREAD

**Issue by Droppix** [WalletConnect/web3modal#888] opened 2023-02-16 10:14 UTC
**Describe the bug**
Hi,

Excellent integration on our side, however, so we are missing a feature: "Localization".
Is there any way to do something? 

**SDK Version**
 - Version [2.1.1]

**Comment by 0xAsimetriq** [comment] 2023-02-16 10:18
closing as duplicate of #627

**Closed by 0xAsimetriq** 2023-02-16 10:18 UTC
Labels: bug
