### ISSUE TITLE
no popup but goes straight to metamask ?

### ISSUE THREAD

**Issue by garyng2000** [WalletConnect/web3modal#230] opened 2021-01-27 16:30 UTC
I tried to follow the simple steps(other than adding WalletConnect) but instead of seeing the popup of providers to select, it kick start metamask immediately.

However, if I tried the .connectTo('walletconnect'), it does show the QR code of WalletConnect.

**Comment by mtsalenc** [comment] 2021-02-15 12:00
I am also experiencing this issue.

**Comment by 640774n6** [comment] 2021-03-01 05:31
Not sure of the root cause of this, but a workaround for me is to  call web3Modal.clearCachedProvider() before web3Modal.connect().

**Comment by jeromevvb** [comment] 2021-03-25 08:34
> Not sure of the root cause of this, but it seems to work for me if I call web3Modal.clearCachedProvider() before web3Modal.connect().

this solution works great, thanks!

**Comment by neuroscr** [comment] 2021-04-30 03:37
`const web3Modal = new Web3Modal({ disableInjectedProvider: true });` maybe of interest too

**Comment by totemgotem** [comment] 2021-06-23 15:40
Hey guys, i got the same issue, with this error msg popping out, any ideas? the solutions posted above didn't really work for me.
![image](https://user-images.githubusercontent.com/85348383/123122402-424bdf80-d446-11eb-9de4-c14647666bd0.png)

**Comment by totemgotem** [comment] 2021-06-24 19:08
You might have found yourself here because you forgot to add the providers specs as they are used here https://github.com/Web3Modal/web3modal/blob/2ff929d0e99df5edf6bb9e88cff338ba6d8a3991/example/src/App.tsx#L235
for me it came bundled with a can't connect to websocket error in console

**Comment by Nazeeh21** [comment] 2021-12-03 06:39
> web3Modal.clearCachedProvider()

This worked for me thanks :)

**Comment by nerdjango** [comment] 2022-01-09 13:14
I can't see my web3modal dialog pop up any help with that?

**Comment by 0xAsimetriq** [comment] 2023-01-21 14:49
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

**Closed by 0xAsimetriq** 2023-01-21 14:49 UTC
Labels: v1
