### ISSUE TITLE
Support browser compatible AMD/UMD standalone js for V2

### ISSUE THREAD

**Issue by jaan** [WalletConnect/web3modal#904] opened 2023-02-23 08:56 UTC
### Link to minimal reproducible example

NA

### Summary

Web3modal v2 has issues with generating standalone js. Could you please provide support for the feature?

Web3modal v1 supports standalone js for browsers
https://unpkg.com/web3modal@1.9.0/dist/index.js

### List of related npm package versions

web3modal@v2.0.0

**Comment by 0xAsimetriq** [comment] 2023-02-23 09:00
Closing as a duplicate of #678

**Closed** 2023-02-23 09:01 UTC
Labels: bug, needs review
